version: '3.8'

services:
    backend:
        container_name: tp1-backend-srv
        image: jossedeoliveiracpe/tp-devops-simple-api:latest
        networks:
         - tp1-net
         - tp1-dbnet
        depends_on:
         - database
        environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=usr
          - POSTGRES_PASSWORD=pwd
          - POSTGRES_HOST=tp1-backend-db:5432

    database:
        container_name: tp1-backend-db
        image: jossedeoliveiracpe/tp-devops-database:latest
        networks:
         - tp1-dbnet
        volumes:
         - tp1-data:/var/lib/postgresql/data
        environment:
         - POSTGRES_DB=db
         - POSTGRES_USER=usr
         - POSTGRES_PASSWORD=pwd
    frontend:
        container_name: tp1-frontend-srv
        image: jossedeoliveiracpe/tp-devops-front:latest
        networks:
         - tp1-net
        depends_on:
         - backend

    httpd:
        container_name: tp1-http-index
        image: jossedeoliveiracpe/tp-devops-httpd:latest
        ports:
         - "80:80"
         - "8080:8080"
        networks:
         - tp1-net
        depends_on:
         - frontend

networks:
  tp1-net:
  tp1-dbnet:
volumes:
  tp1-data: