version: '3.8'

services:
    backend:
        container_name: tp1-backend-srv
        image: jossedeoliveiracpe/tp-devops-simple-api:latest
        networks:
         - tp1-net
         - tp1-dbnet
        depends_on:
         - database

    database:
        container_name: tp1-backend-db
        image: jossedeoliveiracpe/tp1-database:1.0
        networks:
         - tp1-dbnet
        volumes:
         - tp1-data:/var/lib/postgresql/data

    
    frontend:
        container_name: tp1-frontend-srv
        image: jossedeoliveiracpe/tp-devops-front:latest
        networks:
         - tp1-net
        depends_on:
         - backend

    httpd:
        container_name: tp1-http-index
        image: jossedeoliveiracpe/tp-devops-httpd:latest
        ports:
         - "80:80"
        networks:
         - tp1-net
        depends_on:
         - frontend

networks:
  tp1-net:
  tp1-dbnet:
volumes:
  tp1-data: